/**
 * Post-retrain dispatch registry sync — snapshots skill-dispatch routing rows
 * after a successful retrain and exports Cursor/Claude hook files per the
 * dispatch-export-sync SOP.
 *
 * Writes:
 *   - `{cortexDir}/skill-dispatch-registry.json` — routing baseline (local only)
 *   - `{projectRoot}/CLAUDE.local.md` — ## Skills section (gitignored)
 *   - `{cursorPluginRulePath}` — graphnosis-skill-dispatch.mdc trigger table
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { GraphnosisHost } from './host.js';
import type { SkillTrainer } from './skill-trainer.js';
import { baseSkillName, walkSkillSequence, walkSkillToJson } from './skill-trainer.js';

export interface DispatchRouteRow {
  stepIndex: number;
  stepText: string;
  targetSkill?: string;
  targetSourceId?: string;
}

export interface DispatchRegistrySnapshot {
  exportedAt: string;
  skillGraphId: string;
  skillSourceId: string;
  skillName: string;
  routes: DispatchRouteRow[];
  stepCount: number;
}

export interface DispatchExportTargets {
  projectRoots: string[];
  cursorPluginRulePath?: string;
}

export interface DispatchExportResult {
  registry: DispatchRegistrySnapshot | null;
  claudeLocalPaths: string[];
  cursorRulePath?: string;
  cursorrulesPaths: string[];
}

const DISPATCH_SKILL_NAMES = new Set([
  'skill-dispatch',
  'dispatch-export-sync',
]);

const SKILLS_ENGRAM_ID = 'graphnosis-skills';
const GENERATED_MARKER = '<!-- generated by dispatch-export-sync; do not hand-edit -->';
const TARGETS_FILENAME = 'dispatch-export-targets.json';

const CLAUDE_LOCAL_PREAMBLE = [
  'At the start of every coding session, invoke skill-dispatch:',
  '  1. Call list_skills(engram="graphnosis-skills") to confirm skills are loaded.',
  '  2. Call walk_skill_structured on "skill-dispatch" with $currentContext.',
  '  3. Execute all matched skills in the order returned.',
].join('\n');

export function isDispatchRelatedSkill(label: string): boolean {
  const base = baseSkillName(label.replace(/^skill:\d+:/, ''));
  return DISPATCH_SKILL_NAMES.has(base);
}

/** Find the skill-dispatch source in graphnosis-skills (not dispatch-export-sync). */
export function findSkillDispatchSourceId(host: GraphnosisHost, graphId = SKILLS_ENGRAM_ID): string | null {
  if (!host.listGraphs().includes(graphId)) return null;
  for (const src of host.listSources(graphId)) {
    if (src.kind !== 'skill') continue;
    if (baseSkillName(src.ref) === 'skill-dispatch') return src.sourceId;
  }
  return null;
}

/** Extract `- trigger → skill` routing lines from trained skill-dispatch text. */
export function extractDispatchTriggerLines(skillText: string): string[] {
  const lines: string[] = [];
  for (const raw of skillText.split('\n')) {
    const trimmed = raw.trim();
    if (!/^[-—]/.test(trimmed) || !/→/.test(trimmed)) continue;
    // Normalize bullet prefix to "- " for Cursor/Claude exports.
    const normalized = trimmed.replace(/^[-—]\s*/, '- ');
    lines.push(normalized);
  }
  return lines;
}

/** Build Cursor plugin rule body (without YAML frontmatter). */
export function buildCursorDispatchRuleBody(triggerLines: string[]): string {
  const triggers = triggerLines.length > 0
    ? triggerLines.map((l) => l.startsWith('- ') ? l : `- ${l}`).join('\n')
    : '- (no triggers — retrain skill-dispatch)';

  return [
    'graphnosis-skill-dispatch:',
    '',
    'At the start of every coding session, invoke skill-dispatch:',
    '',
    '1. Call `list_skills({ engram: "graphnosis-skills" })` to confirm skills are loaded.',
    '2. Call `walk_skill_structured` on **skill-dispatch** with current context (repo, branch, user request, open todos).',
    '3. Execute all matched skills in the order returned.',
    '',
    'Key triggers (walk skill-dispatch with matching context — it routes automatically):',
    '',
    triggers,
    '',
    'Notes:',
    '',
    '- Autonomous Skill Praxis improvement loop: after executing matched skills, append friction to `sandbox/skill-improvements/<skill-slug>.md`. Retrain at batch boundary on explicit **retrain skills** signal.',
    '- MCP TIMEOUT RULE: retry once on `list_skills` / `walk_skill_structured` timeout; if still failing, route to runtime-diagnosis — never silently skip dispatch.',
    '- PROOF RULE: paste `walk_skill_structured` JSON before writing code when claiming "following skill X".',
    '- Canonical SOPs live in the `graphnosis-skills` engram. Plugin skills are thin wrappers — prefer `walk_skill_structured` over re-reading local SKILL.md when MCP is connected.',
    '- Coding decisions and session notes route to the `coding` engram.',
  ].join('\n');
}

/** Merge or create CLAUDE.local.md with a generated ## Skills section. */
export function mergeClaudeLocalSkillsSection(existing: string, skillsExport: string): string {
  const skillsBlock = [
    GENERATED_MARKER,
    '',
    skillsExport.trim(),
  ].join('\n');

  const sectionRe = /^## Skills\b[^\n]*$/im;
  if (sectionRe.test(existing)) {
    const lines = existing.split('\n');
    const startIdx = lines.findIndex((l) => sectionRe.test(l));
    let endIdx = lines.length;
    for (let i = startIdx + 1; i < lines.length; i++) {
      if (/^##\s/.test(lines[i]!)) {
        endIdx = i;
        break;
      }
    }
    const before = lines.slice(0, startIdx + 1).join('\n');
    const after = lines.slice(endIdx).join('\n');
    const skillsBlock = [
      '',
      CLAUDE_LOCAL_PREAMBLE,
      '',
      GENERATED_MARKER,
      '',
      skillsExport.trim(),
    ].join('\n');
    return [before, skillsBlock, after ? `\n${after}` : ''].join('\n').trimEnd() + '\n';
  }

  const header = existing.trim()
    ? `${existing.trimEnd()}\n\n`
    : '# Personal overrides — gitignored, never committed\n\n';

  return [
    header,
    '## Skills (Graphnosis procedural memory)',
    '',
    CLAUDE_LOCAL_PREAMBLE,
    '',
    skillsBlock,
  ].join('\n').trimEnd() + '\n';
}

/** Splice trigger lines into an existing .mdc rule, preserving frontmatter. */
export function mergeCursorDispatchRule(existing: string, triggerLines: string[]): string {
  const body = buildCursorDispatchRuleBody(triggerLines);
  const fmMatch = existing.match(/^---[\s\S]*?---\n*/);
  if (fmMatch) {
    return `${fmMatch[0]}${body}\n`;
  }
  return body + '\n';
}

/** Resolve export targets from cortex config + env (runtime only — no .env reads). */
export async function resolveDispatchExportTargets(host: GraphnosisHost): Promise<DispatchExportTargets> {
  const projectRoots = new Set<string>();
  let cursorPluginRulePath: string | undefined;

  const configPath = path.join(host.getCortexDir(), TARGETS_FILENAME);
  try {
    const raw = await fs.readFile(configPath, 'utf8');
    const cfg = JSON.parse(raw) as Partial<DispatchExportTargets>;
    for (const root of cfg.projectRoots ?? []) {
      if (typeof root === 'string' && root.trim()) projectRoots.add(path.resolve(root.trim()));
    }
    if (typeof cfg.cursorPluginRulePath === 'string' && cfg.cursorPluginRulePath.trim()) {
      cursorPluginRulePath = path.resolve(cfg.cursorPluginRulePath.trim());
    }
  } catch {
    // Optional config — env vars may still apply.
  }

  const envRoots = process.env.GRAPHNOSIS_DISPATCH_EXPORT_ROOTS;
  if (envRoots) {
    for (const root of envRoots.split(',').map((s) => s.trim()).filter(Boolean)) {
      projectRoots.add(path.resolve(root));
    }
  }

  const envRule = process.env.GRAPHNOSIS_CURSOR_PLUGIN_RULE;
  if (envRule?.trim()) {
    cursorPluginRulePath = path.resolve(envRule.trim());
  }

  return {
    projectRoots: [...projectRoots],
    ...(cursorPluginRulePath ? { cursorPluginRulePath } : {}),
  };
}

/** Build a routing table from a walked skill-dispatch execution plan. */
export function buildDispatchRegistryFromWalk(
  host: GraphnosisHost,
  graphId: string,
  sourceId: string,
): DispatchRegistrySnapshot | null {
  const src = host.getSourceRecord(graphId, sourceId);
  if (!src) return null;
  const walked = walkSkillSequence(host, graphId, sourceId, { recursive: false });
  const title = walked.steps[0]?.text ?? src.ref;
  const plan = walkSkillToJson(walked, { sourceId, title });

  const routes: DispatchRouteRow[] = [];
  for (const step of plan.steps) {
    if (step.calls) {
      routes.push({
        stepIndex: step.index,
        stepText: step.text.slice(0, 200),
        targetSkill: baseSkillName(step.calls.targetTitle),
        targetSourceId: step.calls.targetSourceId,
      });
    }
    for (const p of step.parallel ?? []) {
      routes.push({
        stepIndex: step.index,
        stepText: step.text.slice(0, 200),
        targetSkill: baseSkillName(p.targetTitle),
        targetSourceId: p.targetSourceId,
      });
    }
  }

  return {
    exportedAt: new Date().toISOString(),
    skillGraphId: graphId,
    skillSourceId: sourceId,
    skillName: baseSkillName(src.ref),
    routes,
    stepCount: plan.steps.length,
  };
}

/** Write dispatch registry snapshot to cortex dir after retrain. */
export async function exportSkillDispatchRegistry(
  host: GraphnosisHost,
  graphId: string,
  sourceId: string,
): Promise<DispatchRegistrySnapshot | null> {
  const snapshot = buildDispatchRegistryFromWalk(host, graphId, sourceId);
  if (!snapshot) return null;

  const cortexDir = host.getCortexDir();
  const outPath = path.join(cortexDir, 'skill-dispatch-registry.json');
  await fs.writeFile(outPath, JSON.stringify(snapshot, null, 2), 'utf8');
  return snapshot;
}

/**
 * Export skill-dispatch routing to CLAUDE.local.md, .cursorrules, and the
 * Cursor plugin rule file. Skips paths that aren't configured.
 */
export async function exportDispatchToExternalTargets(
  host: GraphnosisHost,
  skillTrainer: SkillTrainer,
  graphId = SKILLS_ENGRAM_ID,
): Promise<DispatchExportResult> {
  const dispatchId = findSkillDispatchSourceId(host, graphId);
  const result: DispatchExportResult = {
    registry: null,
    claudeLocalPaths: [],
    cursorrulesPaths: [],
  };

  if (!dispatchId) return result;

  result.registry = await exportSkillDispatchRegistry(host, graphId, dispatchId);

  const detail = skillTrainer.getSkill(graphId, dispatchId);
  const triggerLines = extractDispatchTriggerLines(detail?.text ?? '');
  const claudeExport = skillTrainer.exportSkillFromSource(graphId, dispatchId, 'claude-md');
  const cursorrulesExport = skillTrainer.exportSkillFromSource(graphId, dispatchId, 'cursorrules');
  const claudeMd = typeof claudeExport === 'string' ? claudeExport : '';
  const cursorrules = typeof cursorrulesExport === 'string' ? cursorrulesExport : '';

  const targets = await resolveDispatchExportTargets(host);

  for (const root of targets.projectRoots) {
    try {
      const claudePath = path.join(root, 'CLAUDE.local.md');
      let existing = '';
      try { existing = await fs.readFile(claudePath, 'utf8'); } catch { /* create */ }
      await fs.mkdir(root, { recursive: true });
      await fs.writeFile(claudePath, mergeClaudeLocalSkillsSection(existing, claudeMd), 'utf8');
      result.claudeLocalPaths.push(claudePath);

      if (cursorrules) {
        const rulesPath = path.join(root, '.cursorrules');
        const rulesBody = [
          GENERATED_MARKER,
          '',
          cursorrules.trim(),
        ].join('\n');
        await fs.writeFile(rulesPath, rulesBody + '\n', 'utf8');
        result.cursorrulesPaths.push(rulesPath);
      }
    } catch (e) {
      console.warn(`[skill-dispatch-sync] CLAUDE.local export failed for ${root}:`, e);
    }
  }

  if (targets.cursorPluginRulePath) {
    try {
      let existing = '';
      try { existing = await fs.readFile(targets.cursorPluginRulePath, 'utf8'); } catch { /* create */ }
      await fs.mkdir(path.dirname(targets.cursorPluginRulePath), { recursive: true });
      const merged = mergeCursorDispatchRule(existing, triggerLines);
      await fs.writeFile(targets.cursorPluginRulePath, merged, 'utf8');
      result.cursorRulePath = targets.cursorPluginRulePath;
    } catch (e) {
      console.warn('[skill-dispatch-sync] Cursor plugin rule export failed:', e);
    }
  }

  return result;
}

/**
 * After a successful retrain, refresh the dispatch registry and external
 * exports when the skill is skill-dispatch or dispatch-export-sync.
 */
export async function scheduleDispatchSyncAfterRetrain(
  host: GraphnosisHost,
  skillTrainer: SkillTrainer,
  graphId: string,
  sourceId: string,
): Promise<void> {
  const detail = skillTrainer.getSkill(graphId, sourceId);
  if (!detail || !isDispatchRelatedSkill(detail.label)) return;
  const base = baseSkillName(detail.label);

  try {
    const dispatchGraphId = graphId === SKILLS_ENGRAM_ID ? graphId : SKILLS_ENGRAM_ID;
    const exportResult = await exportDispatchToExternalTargets(host, skillTrainer, dispatchGraphId);
    const paths = [
      ...exportResult.claudeLocalPaths,
      ...(exportResult.cursorRulePath ? [exportResult.cursorRulePath] : []),
      ...exportResult.cursorrulesPaths,
    ];
    console.log(
      `[skill-dispatch-sync] registry refreshed for ${base} (${sourceId}); ` +
      `external exports: ${paths.length > 0 ? paths.join(', ') : 'none (configure dispatch-export-targets.json)'}`,
    );
  } catch (e) {
    console.warn('[skill-dispatch-sync] export failed:', e);
  }
}
